### ISSUE TITLE
Format explained?

### ISSUE THREAD

**Issue by BSVogler** [Quantumofcosmos/Visualizing-Whatsapp-chats#1]
Hi!
i wanted to try this program. However I don't have an understanding of R yet and have difficulties running this program.

```
#This script works with a .csv version of the Whatsapp chatlog.
#Use excel or a programm of your choice to separate the raw .txt file by spaces.

```

This is not very helpful. The messages itself contain a lot of spaces. Where do I have to set the spaces? cvs files generally use semicolons or commas. Where should I separate them.
Maybe you can add an example file?

Kind regards

**Comment by Quantumofcosmos** [comment]
Have updated comments in script reflecting the procedure to be followed to change whatsapp text file to csv file.

Revert back i anything else is required. 

cheers.

**Comment by BSVogler** [comment]
It would be nice if this software would not depend on proprietary software like MS Excel. I don't have a copy of MS Excel installed and I think it should be possible to simply use _search and replace_ of a text editor.
